apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-tech-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mithunraj-mithu/noosphere-bootstrap-mithun
    targetRevision: HEAD
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: grade-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true